# Generated by Django 3.2 on 2021-04-24 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qv1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='quiz',
        ),
    ]
