# Generated by Django 3.2 on 2021-04-24 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qv1', '0002_remove_question_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='qv1.quiz'),
            preserve_default=False,
        ),
    ]
