# Generated by Django 3.2 on 2021-04-24 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qv1', '0003_question_quiz'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='quiz',
            new_name='quiz_id',
        ),
    ]
