# Generated by Django 3.2 on 2021-04-24 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qv1', '0004_rename_quiz_question_quiz_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='quiz_id',
            new_name='quiz',
        ),
    ]
